title: Sophie Youk # name
logo: "profile2.jpg?raw=true" # photo
description: > # text
  Master student in Statistics >
  at University of Virginia >
  expecting to graduate in December 2020
  <br><br>
  Programming Languages: R, SAS, Python, SQL, JMP, Java >
  Algorithms: PCA, LDA, QDA, Multivariate Logistic, Time Series Analysis, Bootstrap, Clustering, Random Forest
  <br><br>
  <a href="https://www.linkedin.com/in/syouk/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
