title: Sophie Youk # name
logo: "profile2.jpg?raw=true" # photo
description: > # text
  University of Virginia
  <br>
  August 2019 - December 2020
  <br>
  M.S. in Statistics
  <br><br>
  University of Georgia
  <br>
  August 2015 - May 2018
  <br>
  B.S. in Statistics
  <br><br>
  <a href="https://www.linkedin.com/in/syouk/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.github.com/sophieyouk/">View My GitHub Profile</a>

theme: jekyll-theme-minimal
