title: Sophie Youk # name
logo: "profile2.jpg?raw=true" # photo
description: > # text
  <strong>M.S. in Statistics</strong> <em>Aug. '19 - Dec. '20</em>
  <br>
  University of Virginia
  <br>
  <strong>B.S. in Statistics</strong> <em>Aug. '15 - May '18</em>
  <br>
  University of Georgia
  <br><br>
  <a href="https://www.linkedin.com/in/syouk/">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/sophieyouk/">View My GitHub Profile</a>

theme: jekyll-theme-minimal
